### ISSUE TITLE
(Suggestion) make it available on Edge store

### ISSUE THREAD

**Issue by dnet890** [MostwantedRBX/proton-chrome-extension#9]
Hi
Since Google policy is sometimes ambiguous and cause false flag to many extensions,  it will great to support Edge store as well

**Comment by MostwantedRBX** [comment]
Sorry it's been a while! I actually plan on adding this for all major browsers. Just gotta do a bit of research first!

**Comment by MostwantedRBX** [comment]
I submitted the extension for review for Edge. I will let you know when the process is complete. Thank you for showing interest in the extension. :)
@dtantono

**Comment by MostwantedRBX** [comment]
The extension is now on edge. :)

https://microsoftedge.microsoft.com/addons/detail/efggpghjemjhldhoemgijjpnajcidcni
